package ExamenSemanaSantaExcepciones;

public enum DiaSemanaSanta {
	DOMINGO_RAMOS, LUNES_SANTO, MARTES_SANTO, MIERCOLES_SANTO, JUEVES_SANTO, MADRUGA, VIERNES_SANTO, SABADO_SANTO,
	DOMINGO_RESURRECCION
}
